apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ${BUILD_CONFIG_NAME}
  namespace: ${NAMESPACE}
  labels: { app: ${APP_NAME} }
spec:
  source:
    type: Binary
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: ${BUILDER_IS_NAMESPACE}   # ← 추가
        name: ${BUILDER_IS_NAME}:${BUILDER_IS_TAG}  # ← 추가
  output:
    to:
      kind: ImageStreamTag
      name: ${APP_NAME}:${OUTPUT_IMAGE_TAG}
  triggers:
    - type: ConfigChange

